version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
